Repository Datateknologerna-vid-Abo-Akademi/date-website, pull requests merged in 2024-01, with the labels that each got.

#419 I'm a teapot
  core/settings.py
  core/templates/418.html
  date/middleware.py
Labels: feature, benna

#386 Feat/Check if user has active subscription when signing up for event
  events/views.py
Labels: feature

#434 Feat: Allow editing event signup preferences
  events/admin.py
  events/static/prettyjson/prettyjson.js
  events/widgets.py
Labels: feature

#450 Add caching to rarely updated pages
  core/settings.py
  date/views.py
  docker-compose.yml
  events/urls.py
  news/views.py
  staticpages/urls.py
Labels: fix

#464 Fix websockets
  events/consumers.py
  events/views.py
Labels: bug

#433 feat: Celery mail
  archive/models.py
  core/.env
  core/__init__.py
  core/celery.py
  core/settings.py
  core/urls.py
  core/utils.py
  docker-compose.yml
  example.env
  members/forms.py
  members/models.py
  members/templates/registration/password_reset_email.html
  members/urls.py
  members/views.py
  requirements.txt
Labels: feature

#457 Custom change password template + button to userinfo
  members/static/members/style.css
  members/templates/registration/password_change_done.html
  members/templates/registration/password_change_form.html
  members/templates/userinfo.html
  members/urls.py
  members/views.py
Labels: feature, first issue
