Repository Datateknologerna-vid-Abo-Akademi/date-website, pull requests merged in 2024-03, with the labels that each got.

#519 update to ckeditor 5
  core/settings.py
  core/templates/static/css/ckeditor.css
  core/urls.py
  ctf/migrations/0003_alter_ctf_content_alter_flag_clues.py
  ctf/models.py
  events/migrations/0013_alter_event_content.py
  events/models.py
  news/migrations/0003_alter_post_content.py
  news/models.py
  requirements.txt
  staticpages/migrations/0004_alter_staticpage_content.py
  staticpages/models.py
Labels: fix, dependencies, Blocker

#453 Fix/280 fix clean up the spaghetti in eventsviewspy
  events/tests.py
  events/views.py
  events/websocket_utils.py
Labels: needs testing, Blocker

#456 exclude_indexing and update details template
  events/models.py
  events/templates/events/detail.html
Labels: Blocker

#535 401 for incorrect passcode
  events/tests.py
  events/views.py
Labels: fix

#536 Center text on news page with no content
  news/templates/news/index.html
Labels: first issue, fix, KK, DATE, BIOCUM
