Repository Datateknologerna-vid-Abo-Akademi/date-website, pull requests merged in 2024-04, with the labels that each got.

#546 Create news categories
  news/admin.py
  news/forms.py
  news/migrations/0004_category_post_category.py
  news/models.py
Labels: backend-merge, Blocker

#550 Migrate static page foreignkey lins to url links
  staticpages/migrations/0005_staticpage_nav_to_url.py
Labels: fix, backend-merge

#596 Change redis image to the valkey fork
  docker-compose.yml
Labels: dependencies

#602 Fix/random styling issues
  static/common/core/css/header.css
  static/common/events/css/detail.css
  static/date/date/css/date-root.css
  static/date/date/css/homepage.css
  templates/common/core/footer.html
  templates/date/date/start.html
  templates/demo/date/start.html
Labels: UI/UX, fix

#603 Fixed demo, #545
  static/date/date/css/homepage.css
  static/demo/date/css/date-root.css
  static/demo/date/css/homepage.css
  templates/demo/date/start.html
Labels: UI/UX, fix
